# server application
spring.application.name: =artifactId=
spring.mvc.favicon.enabled: false
server.port: 16001

# logger, to see logback-spring.xml
logging.level: INFO
logging.level.app: DEBUG

spring.redis.host: 127.0.0.1
spring.redis.port: 6379
spring.redis.password:

spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.12.207.243:3306/uzblog?useSSL=false&characterEncoding=utf8
      username: root
      password: Abc1234567!
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.13.119.103:3306/uzblog?useSSL=false&characterEncoding=utf8
      username: root
      password: Feng!2019

uzshare.static.path: /web/uzshare/static/
sitemap.sites: uzzz.org.cn,uzshare.com,www.uzshare.com
uzzz.path: /web/uzzzz.github.io

hadoop.sort.path: /web/uzsupport/hadoop/sorter.out/
hadoop.duplicate.path: /web/uzsupport/hadoop/duplicate.out/
hadoop.semblance.path: /web/uzsupport/hadoop/semblance.out/

weixin.url: https://mp.weixin.qq.com
image.proxy: https://ss.csdn.net/p?
