# logger, to see logback-spring.xml
logging.level: INFO
logging.level.app: DEBUG

spring:
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.13.68.122:3306/uzblog?useSSL=false&characterEncoding=utf8
      username: root
      password: Abc1234567!
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.13.68.122:3306/uzblog?useSSL=false&characterEncoding=utf8
      username: root
      password: Abc1234567!