# server application
server.port: 16001
spring.application.name: =artifactId=
spring.mvc.favicon.enabled: false

server.use-forward-headers: true
server.tomcat.protocol_header: X-Forwarded-Proto
server.tomcat.remote_ip_header: X-Forwarded-For
server.tomcat.port-header: X-Forwarded-Port

spring.profiles.active: =build.profile.id=

spring.redis.host: 127.0.0.1
spring.redis.port: 6379
spring.redis.password:

spring.jpa.hibernate.ddl-auto: update

uzshare.static.path: /web/uzshare/static/
sitemap.sites: uzshare.com
uzzz.path: /web/uzzzz.github.io
uzzz.org.path: /web/uzzz.org.github.io

hadoop.sort.path: /web/uzsupport/hadoop/sorter.out/
hadoop.duplicate.path: /web/uzsupport/hadoop/duplicate.out/
hadoop.semblance.path: /web/uzsupport/hadoop/semblance.out/

weixin.url: https://mp.weixin.qq.com
image.proxy: https://ss.csdn.net/p?